#!/usr/bin/env bash
echo '-----> 1'
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
echo '-----> 2'
APP="$1";  IMAGE="dokku/$APP"
echo '-----> 3'

RUN=$(cat <<EOF
echo '-----> 4'
PATH=$PATH:/app/vendor/node/bin &&
echo '-----> 5'
cd /app &&

sleep 1

echo '-----> gulp build'
./node_modules/gulp/bin/gulp.js build
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$RUN")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
